---
title: "Home"
format: 
  html:
    toc: true
---

This [repository](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm) contains model developments for 2025 Southwest Pacific Ocean Bayesian Surplus Production Model (BSPM) striped marlin stock assessment conducted in collaboration by the Pacific Community ([SPC](https://fame.spc.int/key-work-areas/stock-assessment)) and [NOAA Fisheries](https://www.fisheries.noaa.gov/about/pacific-islands-fisheries-science-center).

The assessment report presented and submitted to WCPFC SC21 is available on [GitHub](https://n-ducharmebarth-noaa.github.io/2025-swpo-mls-bspm/assets/swpo-mls-bayesian-assessments.html) and the [WCPFC SC21](https://meetings.wcpfc.int/node/26683) meeting page. Additionally, the assessment presentation to WCPFC SC21 is available below.

<br>

## Presentation

{{< revealjs file="assets/sc-pres.html" height="500px" class="ratio ratio-16x9" >}}

<br>

## Reproducible Analysis with TAF

This repository implements the [TAF](https://cran.r-project.org/package=TAF) (Transparent Assessment Framework) standard for reproducible stock assessments. The TAF framework extracts model data and results into standardized CSV formats that can be easily examined using Excel, R, or other statistical software.

**Getting Started:**

- Users can reproduce the diagnostic model by running [`00a_start_here.R`](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm/blob/main/taf/r_code/00a_start_here.R) (~30 minutes)
- Users can reproduce the full model ensemble by running [`00b_start_here.R`](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm/blob/main/taf/r_code/00b_start_here.R) (~120 minutes)

The project uses [`renv`](https://rstudio.github.io/renv/articles/renv.html) for package management to ensure reproducibility across different computing environments. See the repository [README](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm/blob/main/README.md) for detailed setup instructions.

::: {.callout-note collapse="false"}
## Note

Running the assessment model through the TAF framework will result in minor differences (affecting the 2nd or 3rd decimal place) of [key management quantities](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm/blob/main/taf/output/ens_mgmt_summary.csv) despite all data, model settings and initial conditions being identical. This is due to differences in the random number generator used to set-up the parallel sampling of the posterior distribution. If the exact quantities are desired, as matching the report, please refer to the [main development version of the file](https://github.com/N-DucharmeBarth-NOAA/2025-swpo-mls-bspm/blob/main/data/output/ens_mgmt_summary.csv).
:::

<br>

## Acknowledgements {.narrow-left-bg-image .smaller}

[Collaborative Assessment Process]{.blue}

This assessment greatly benefited from collaboration with a broad group of interested parties and stock assessment experts where feedback was provided in an iterative manner throughout the model development process. Leveraging their diverse expertise helped produce a stronger scientific product.

[Special thanks to:]{.blue}

K. Kim (SPC), N. Davies (Te Takina Ltd.), S. Hoyle (Hoyle Consulting), R. Ahrens (PIFSC), and M. Nadon (PIFSC)

for their insights and thoughtful discussion which improved the assessment!

<br>

## Disclaimer

Many runs contained within this repository represent preliminary model explorations and should not be used '*as is*' for the consideration of management advice. Only models that have been presented and accepted to the [WCPFC](https://www.wcpfc.int/) Scientific Committee should be used as the basis for management advice.
